### ISSUE TITLE
Volume for selection wand is inconsistent

### ISSUE THREAD

**Issue by 14ercooper** [14ercooper/14erEdit#1]
**Describe the bug**
The volume of the selection region changes if you switch positions 1 and 2 with each other.

**To Reproduce**
1. Get a selection wand.
2. Create a region, noting the volume.
3. Swap position one and two.
4. The volume is now different but should be the same.

**Expected behavior**
The volume should be the same.

**Attempted Workarounds (please note if any workarounds were successful**
The issue involves the code that accounts for if one of the coordinates is negative.
This is also present while expanding a selection.

**Screenshots**
None.

**System (please complete the following information):**
 - Spigot Version: 1.14.2
 - Java Version: 8
 - Version: v0.0.4-SNAPSHOT

**Additional context**
None.

**Comment by Racerdude24** [comment]
What is the purpose of the volume function? Is it supposed to return the L x W x H of the selection box? Because if so then I rarely get the correct response.

**Comment by 14ercooper** [comment]
The intended function is to get the number of blocks in the box (which is as you said).
It really isn't very accurate, considering it just needs to do some multiplication. Hence the bug report.

**Comment by NotQuiteAmish** [comment]
Ok I issued a pull request that I believe will fix the issue.
