### ISSUE TITLE
GetBlockData operator returns leaf data twice

### ISSUE THREAD

**Issue by 14ercooper** [14ercooper/14erEdit#11]
**Describe the bug**
Using the GetBlockData operator on a leaf block returns the data twice.

**To Reproduce**
1. Create a brush with the GetBlockData operator.
2. Use the brush on a lead.

**Expected behavior**
The data for the leaf should have only been returned once.

**Attempted Workarounds (please note if any workarounds were successful**
Could ignore it, but I can't figure out where the second print text call is coming from.

**Screenshots**
None.

**System (please complete the following information):**
 - Spigot Version: 1.14.2
 - Java Version: 8
 - Version v0.0.4-SNAPSHOT

**Additional context**
None.

**Comment by NotQuiteAmish** [comment]
I am unable to reproduce the bug. 

I have used the brushes `/fx br s 0 0.5 <<` and `/fx br d 0 <<`, but both seem to return the leaf data only once as intended.
![Functioning Brush](https://user-images.githubusercontent.com/25289989/59066363-e1f89e00-887c-11e9-8725-1ac934a6ba82.PNG)

**Comment by 14ercooper** [comment]
The brush `/fx br s 1 -0.5 <<` seems to return it twice.
![Minecraft Screenshot 2019 06 06 - 19 41 18 63](https://user-images.githubusercontent.com/4555278/59076447-58a09600-8893-11e9-8751-f510e4a049ba.png)
