### ISSUE TITLE
"set" not working with blockstates

### ISSUE THREAD

**Issue by erismc** [14ercooper/14erEdit#119]
**Describe the bug**
When specifying a block state to use in a set operation, the operation breaks

**To Reproduce**
/fx br s 10 0.5 if both air at 0 -1 0 purple_concrete set oak_slab[type=top]

**Expected behavior**
This should set air blocks above purple_concrete to being a top oak slab.

**Attempted Workarounds (please note if any workarounds were successful**
Attempted to set the block as oak_slab (worked fine) and then update the blockstate with "/fx br s 10 0.5 if oak_slab set [type=top]

**Screenshots**

**System (please complete the following information):**
 - Spigot Version: 1.16.5 - 14eredit beta branch
 - Java 8
 - Using the Megaserver

**Comment by 14ercooper** [comment]
Cannot reproduce error. Command given seems to work as expected on the latest beta build.
![2021-03-08_11 02 19](https://user-images.githubusercontent.com/4555278/110361962-eaf04380-7ffd-11eb-8968-f3ebd81ceca8.png)
