### ISSUE TITLE
Autofill block IDs after "set" operation

### ISSUE THREAD

**Issue by erismc** [14ercooper/14erEdit#126]
**Is your feature request related to a problem? Please describe.**
Typing commands is a pain, particularly for blocks with long ids (eg. polished_blackstone_brick_stairs), often make a mistake somewhere and it's hard to figure out where sometimes.

**Describe the solution you'd like**
autofill suggestions from all block ids after the "set" operator

**Describe alternatives you've considered**
using world edit

**Additional context**
I know that autofill has been brought up before, but because of the way commands are structured it would be difficult to implement, however I think if it is limited to suggesting block names after set that would make using 14eredit much faster.

**Comment by 14ercooper** [comment]
Autofilling block IDs resulted in a very messy output, and wasn't helpful with multi-block commands either. Wontfix.

**Comment by erismc** [comment]
This wontfix keeps me up at night
