### ISSUE TITLE
functions: change "dimensions" on getpos to x y and z

### ISSUE THREAD

**Issue by enshano** [14ercooper/14erEdit#129]
while !getpos works just fine, it's unwieldy to use 0, 1, and 2 to represent directions such as x, y, and z, considering the similar use of 0, 1, and 2 as user-input variables in !getvar. there's no logical reason not to change 0, 1, and 2 to their letter counterparts, and it would make it far clearer to use. OG minecrafters may also recall "/gamemode 0," 1, and 2, and the nether and end are also, similarly, dimensions referred to as 0, 1, and 2, something that vastly confused me when first trying to understand !getvar. changing this to x, y, and z would negate that confusion.

**Comment by 14ercooper** [comment]
Wontfix - getpos pulls from variables not the user input (since you can put a numeric literal into a variable).
