### ISSUE TITLE
Autofill valid file names for schematics, ops, templates, multibrushes, functions, etc

### ISSUE THREAD

**Issue by erismc** [14ercooper/14erEdit#133]
**Is your feature request related to a problem? Please describe.**
I have a lot of schematics and other 14eredit files, remembering the names (particularly of the longer ones) is hard and can be slow. Often have to look up the names in the folder structure.

**Describe the solution you'd like**
It would be great (and faster) if there was an autofill of the valid file names that appeared after the relevant operations.

**Describe alternatives you've considered**
Looking up the names in the existing folder structure, more annoying to do since I started mapping on an external server and not just the MMS. This is also much more annoying to do when working on a single screen.

**Additional context**
14erEdit best mapping plugin xoxo

(does flattery help get features implemented? probably not. But it's true. Just don't tell Nava I said it)

**Comment by 14ercooper** [comment]
Has been resolved with the addition of autofill in v1.8.0
