### ISSUE TITLE
functions: change !getpos to !getpos (player) and !getblpos

### ISSUE THREAD

**Issue by enshano** [14ercooper/14erEdit#134]
!getpos receives the block position when nested into an operation and receives the player position when affected on its own. This is confusing _and_ limiting. Instead, you could have !getpos and !getblx, both of which could work in a nested function, but for which !getblx would send an error when used in /funct.

I honestly don't know what the use could or would be for a user-only !getpos in a nested function but I know I'll run into one sooner rather than later. And this ties into my next ticket! wooooooooo

**Comment by 14ercooper** [comment]
!getpos is working as intended - getting the position the function is being run from
