### ISSUE TITLE
server crashed *wooooo*

### ISSUE THREAD

**Issue by enshano** [14ercooper/14erEdit#139]
**Describe the bug**
server crashed while trying to use a function as a number node

**To Reproduce**
first try, that gave me error 1331:
/fx br s 5 0.5 _ 1 fx SineXat 3 4 5 3 set glass_block
second try, that just straight crashed the server:
/fx br s 5 0.5 ^ 1 fx SineXat 3 4 5 3 set glass_block

**Expected behavior**
waves of glass, i think? pillars of glass? something or other.

**Attempted Workarounds (please note if any workarounds were successful**
the second try was an attempted workaround of error 1331, which i don't have context for. but it crashed the server.

**Additional context**
I checked the megaserver terminal log and it looks like the error came from running the function multiple times over, as it tends to do when working with ranges (i'd assume). The server didn't respond for several seconds, and then it crashed. I closed the server too soon to see what was going on beyond that, but i saw it running through the function maybe 100 times over.

it's impolite to swear in a github bug report but i want you to know that there's a swear in my soul

**Comment by 14ercooper** [comment]
Wontfix. Error is not in function, but rather 2 errors in command. First, both _ and ^ require a range node (not provided), and second the block is `glass` not `glass_block`
