### ISSUE TITLE
The Catenary script does not start and end at the points selected / not being symmetrical

### ISSUE THREAD

**Issue by erismc** [14ercooper/14erEdit#141]
**Describe the bug**
catenaries drawn by "/script catenary purple_concrete -100" do not start and end at the points selected by the selection wand, which therefore gives assymetrical outputs which fill me with sadness!!!

**To Reproduce**
1. Select two points in a straight line that is 15 blocks long, inclusive, using the selection wand
3. use the catenary script
4. See badness

**Expected behavior**
Symmetrical shapes when height of start and end point are the same, start and end point actually matching the points selected

**Attempted Workarounds (please note if any workarounds were successful**
Making the arch, selecting half of it

**Screenshots**
![2021-04-07_19 42 03](https://user-images.githubusercontent.com/79383337/113918462-5f272e00-97da-11eb-9d56-032a9d9af8a3.png)

![2021-04-07_19 39 29](https://user-images.githubusercontent.com/79383337/113918440-5a627a00-97da-11eb-8e78-a207671477d7.png)

**System (please complete the following information):**
"This server is running Paper version git-Paper-576 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 8 version(s) behind
Previous version: git-Paper-570 (MC: 1.16.5)"
I'm running the 14eredit-beta from ~ 2 weeks ago, the version before the change to cap macros at 2 per second.

**Additional context**
You have beautiful eyes, Logan : )

**Comment by erismc** [comment]
A similar bug seems to occur with line macros, where they draw from a block lower and offset from where you're aiming. I'm not sure if it's the same bug causing this or not, if not - I can submit a different bug report

**Comment by 14ercooper** [comment]
These two issues both stem from the same underlying issue
