### ISSUE TITLE
functions: blocks in function parameters

### ISSUE THREAD

**Issue by enshano** [14ercooper/14erEdit#166]
hypothetically, if i were checking to see where i'd misplaced a block in my concentric circles of x radius centered around me at !getpos, i'd want to be able to specify the block i was using so that i didn't have to reload the server to change it. so i'd want to do something like /funct CheckCircles 2 <radius> black_concrete.

this means that we'd need to be able to parse $1 as a block. this also means that !blk black_concrete $v0 $v1 $v2 should also work as !blk $1 $v0 $v1 $v2, because i don't think putting a block into a variable is worth the trouble.

(yes, this does work in tandem with !exit [blockvar], because we'd want to be able to input a certain block to produce in shapes or calculations. yes, this is annoying. no, i am not sorry.)

**Comment by 14ercooper** [comment]
This sort of template variables uses a simple text replace, so you can pass whatever you want into it.
