### ISSUE TITLE
/template list and /template <filename> args

### ISSUE THREAD

**Issue by erismc** [14ercooper/14erEdit#178]
**Is your feature request related to a problem? Please describe.**
It's easy to forget the exact name of a template file and easy to forget the number . As the easiest way to make brushes for other people to use I think it would be useful to be able to check the available templates and how many arguments a specific template needs

**Describe the solution you'd like**
"/template list" would list the template brushes loaded currently, similar to /fx schem list.

"/template <filename> args" would give the number of arguments the brush wants (4)

**Describe alternatives you've considered**
Use my sieve-like memory

**Comment by 14ercooper** [comment]
What if they make a template called args or list? Wontfix
Note: /template will now autocomplete template names anyways
