### ISSUE TITLE
/re doesn't retain block data

### ISSUE THREAD

**Issue by Tristinack** [14ercooper/14erEdit#19]
After placing some random glow lichen using a 14eredit brush and switching to a WE brush after, I accidentally used the wrong undo command while attempting to undo my WE brush. Noticing my error, I ran /re 9 to bring back the glow lichen. To my surprise, the glow lichen did not come back on the correct block face because they did not retain the [down=true] tag. While writing this I quickly checked this issue with bubble coral [waterlogged=false] and sure enough, after undoing and redoing, it is waterlogged.
![2022-02-09_06 05 29](https://user-images.githubusercontent.com/77240102/153217113-238a2494-15c4-423f-9463-58f5d8aecca6.png)

**Comment by 14ercooper** [comment]
Definitely a bug, I thought I fixed all spots where this could happen but apparently not. I'll work on fixing it.
