### ISSUE TITLE
Selection wand position 2 updated twice

### ISSUE THREAD

**Issue by 14ercooper** [14ercooper/14erEdit#2]
**Describe the bug**
The second position on the selection wand gets updated twice when you change the position.

**To Reproduce**
1. Get a selection wand.
2. Move the second position.

**Expected behavior**
The position should only get updated once.

**Attempted Workarounds (please note if any workarounds were successful**
Ignore the second message, since it sets it to the same position as the first. Not sure where in the code the second message comes from.

**Screenshots**
None.

**System (please complete the following information):**
 - Spigot Version: 1.14.2
 - Java Version: 8
 - Version: v0.0.4-SNAPSHOT

**Additional context**
None.

**Comment by NotQuiteAmish** [comment]
I believe this issue was fixed with a commit during when bug-fixing was a branch?
