### ISSUE TITLE
Brushes operate based on changes already made by brush

### ISSUE THREAD

**Issue by NotQuiteAmish** [14ercooper/14erEdit#27]
**Describe the bug**
Blocks affected by a brush that uses nearby blocks such as the "blocks below" ( _ ) node are evaluated with regards to blocks already changed by the brush. So blocks that did not have the correct "blocks below" requirement are being operated on because they do once blocks below them are affected earlier on in the brush process.

**To Reproduce**
1. Create a "blocks below" brush (e.g.  /fx br s 5 0.5 ? _ - 1 1 ~ air > stone false)
2. Use brush on a level surface
3. Blocks will be affected in a full sphere

**Expected behavior**
Only blocks on the bottom layer of the sphere brush should be affected

**Attempted Workarounds (please note if any workarounds were successful**
Use advanced brushes that check for the block type being placed

**System (please complete the following information):**
 - Spigot Version: 1.14.2
 - Java Version: 11.0.3
 - Version: 0.0.7-SNAPSHOT

**Additional context**
This is likely due to the blocks being operated on sequentially, and is likely not only limited to the blocks below node, but any other brush that checks the blocks around it.

**Comment by 14ercooper** [comment]
Since I just assigned this to myself, I'm going to make a quick note of how I'm going to fix it.
Snapshot brush sphere (like the one used for undo would work) and operate based on the contents of the snapshot kinda like the erosion macro.
This will require a bit of a rework of the entire brush system.
