### ISSUE TITLE
Ability to execute a brush stroke with a command block or datapack

### ISSUE THREAD

**Issue by GavstarB** [14ercooper/14erEdit#35]
**Is your feature request related to a problem? Please describe.**
Brush execution requires an opped player to be present. This is not really a problem so much as a limitation

**Describe the solution you'd like**
Adding the ability to execute a specific brush via a command

e.g. "executebrush [x] [y] [z] [brush syntax]"

**Describe alternatives you've considered**
The alternative is to have a player present to execute the brush strokes

**Additional context**
This feature would allow for series of operations in different locations to be executed via datapacks in a single function call, which could allow for the procedural generation of areas without a player present. It also allows performance-dropping brushes (such as those with a large radius) to be executed from the server console with no players online

**Comment by 14ercooper** [comment]
This is a bit tricky, as if there isn't a player; what player should be able to undo the edit?
