### ISSUE TITLE
fx sel pos setting coordinates to given values rather than just player

### ISSUE THREAD

**Issue by lifeofchrome** [14ercooper/14erEdit#39]
**Describe the bug**
Using `/fx sel pos1 <x> <y> <z>` and pos2 before having a selection box doesn't work and says `Usage: /fx <subcommands>`.

**To Reproduce**
1. Start or relog into a Spigot server with 14erEdit
2. Try executing `/fx sel pos1 1 1 1`
3. See error

**Expected behavior**
The position should be set

**Attempted Workarounds (please note if any workarounds were successful)**
Use the selection wand

**Screenshots**
![image](https://user-images.githubusercontent.com/8226943/75637394-e2477f00-5beb-11ea-9a4e-09fa369499ce.png)

**System (please complete the following information):**
 - Spigot Version: 1.15.2
 - Java Version: 8
 - 14erEdit Version: v1.1.2

**Comment by 14ercooper** [comment]
This isn't even functionality that command is intended to have. Changing this from a bug report to a feature request.
