### ISSUE TITLE
Blobby brush

### ISSUE THREAD

**Issue by 14ercooper** [14ercooper/14erEdit#49]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
A new brush type that acts to make several sphere strokes near a central location

**Describe alternatives you've considered**
Manually use multiple sphere brush strokes

**Additional context**
None

**Comment by sw3aterCS** [comment]
Isn't this achieved using the `splatter` brush? Or, is your brush idea for something similar but different?

**Comment by 14ercooper** [comment]
Ah yeah I guess I just forgot to reference this issue in that commit so it never got closed
